### ISSUE TITLE
Preparation(How to cook) instructions issue

### ISSUE THREAD

**Issue by bluerainmango** [fguzmanrs/eclecticKitchen#29]
The code for a Collapsible accordion(instruction part) has been added to Backend5 as our original plan. 

But, I think the Card component's Reveal functionality would be more suitable for our recipes. 
As Fabi and Hayden are already implementing Card component to our HTML/JS so just a little bit of tweak on your code would be enough to add this functionality. If you need help, let me know. 

Below images are what I roughly tested and compared two functionalities. 

**▼ Card's Reveal**
![card-demo](https://bluerainmango.github.io/imgs/card-demo.gif)
**▼ Collapsible accordion**
![collapsible-demo](https://bluerainmango.github.io/imgs/collapsible-demo2.gif)

**Comment by ffortizn** [comment]
Nice! I tried to make it work, no luck. :(
Yours look awesome. :)

 Francisco Ortiz
 Email: ffortizn@gmail.com
