### ISSUE TITLE
Spoonacular Sign up for api key

### ISSUE THREAD

**Issue by bluerainmango** [fguzmanrs/eclecticKitchen#4]
The free plan provides only 150 requests a day. All members need to sign up and generate api keys to test the app enough. 

https://spoonacular.com/food-api

**Useable API endpoints:
- Search Recipes by Ingredients
- Get Analyzed Recipe Instructions or Summarize Recipe

**Comment by fguzmanrs** [comment]
API Key: d0aef524cfc14d6ba3f35bc68ab620b9

**Comment by HCross28** [comment]
Hayden API Key: 06238180649d43e0bffc9f3ac6536dc3
